# Generated by Django 5.0.6 on 2024-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receipt',
            field=models.CharField(default='', max_length=60, verbose_name='收件人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='留言內容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=128, verbose_name='留言主題'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=50, verbose_name='留言者'),
        ),
    ]
